name: build-influxd
on:
  workflow_dispatch: {}
  push:
    branches: [dev-add-flux-profiler-support_CI]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/influxdb/cross-builder:go1.24.13-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build influxd
        run: |
          export GOOS=linux GOARCH=arm64 CGO_ENABLED=1
          export CC="$(xcc linux aarch64)"
          rustlib="$(find_rustlib_path aarch64-unknown-linux-musl)"
          ldflags='-s -w -linkmode=external -extld='"${CC}"' -extldflags "-fno-PIC -static-pie -Wl,-z,stack-size=8388608 -L'"${rustlib}"' -Wl,-lunwind"'
          go build \
            -tags="netgo,osusergo,static_build" \
            -buildmode=pie \
            -ldflags="${ldflags}" \
            -o influxd \
            github.com/influxdata/influxdb/cmd/influxd
      - uses: actions/upload-artifact@v4
        with: { name: influxd, path: influxd }
